- src/advanced/node-management.md
Checked grammar, clearness of language and conducted semantic analyses of ambiguous parts.
> proofreading of node-management

- src/architecture/configuration.md
- src/architecture/services.md
> Configuration improvements

- src/glossary.md
adjusted defention of a "full node" due to corrections in "system configuration" document
> add "aka peer" to "full node" defenition

- src/architecture/configuration.md
Checking grammar, eliminating inconsistences in essence, unifying terminology
> proofreading configuration-improvement

- src/contributing.md
- src/get-started/install.md
...from the Install article to the contribution guide.
Closes #116.
> Move clippy and rustfmt installation guide

- README.md
This PR adds badges to README and otherwise prepares README to after-publishing activities.
Shouldn't be merged until after publishing.
> Prepare README for publishing

- .editorconfig
- .travis.yml
- README.md
- dev-requirements.txt
- misc/lock.py
- requirements.lock
- requirements.txt
This PR improves dependency management in the repository. Among other things, it introduces a lockfile for dependencies, which could be useful in production deployment.
> Dependency management

- requirements.txt
- src/architecture/transactions.md
> Remove bogus example for info method

- src/get-started/create-service.md
...according to changes made by exonum/cryptocurrency#29.
> Update "Create service" tutorial with info on read requests

- src/get-started/create-service.md
...according to exonum/cryptocurrency#35.
> Update tutorial to make Wallet immutable

- src/get-started/create-service.md
This PR updates the service tutorial to version 0.3 (commit exonum/cryptocurrency@c05d2680014bd5f6741677c5c0ac742eb49daa47).
> Update service tutorial to 0.3

- src/get-started/create-service.md
...according to changes brought by exonum/cryptocurrency#44.
> Update API section of tutorial

- src/get-started/design-overview.md
- src/get-started/what-is-exonum.md
- src/index.md
Hi! I am not a native speaker myself, but I hope most of these changes are correct :) Feel free to ask clarifications about particular edits, maybe some of them are wrong.
> Slight wording tweaks

- src/architecture/configuration.md
> Describe CORS settings

- src/advanced/node-management.md
See https://github.com/exonum/exonum-testkit/pull/20
> Document 'healthcheck' public endpoint

- src/architecture/serialization.md
This PR updates the serialization page according to recent changes to the core (referenced in separate commits).
Related to #154.
> Update serialization page

- src/advanced/service-testing.md
See https://github.com/exonum/exonum-testkit/pull/27
> Mention testkit logging in tutorial

- src/get-started/install.md
Complementary to exonum/exonum#472.
> Clarify supported Rust versions

- src/advanced/configuration-updater.md
Update of documentation according to https://github.com/exonum/exonum-configuration/pull/83
> Rename num_votes to num_validators

- src/contributing.md
- src/get-started/design-overview.md
This PR references the contributing documents recently introduced or updated in the Exonum repo.
Related to exonum/exonum#482, exonum/exonum#463.
> Reference repo documents

- src/advanced/node-management.md
> Document shutdown endpoint [ECR-824]

- src/get-started/install.md
> Update Installation Guide

- mkdocs.yml
- theme/main.html
Change site canonical URL https://exonum.com/doc/ to https://exonum.com/doc to fix sitemap.xml:
```xml
<loc>https://exonum.com/doc//get-started/what-is-exonum/</loc>
```
> fix canonical url

- misc/lint.sh
- mkdocs.yml
- src/advanced/node-management.md
- src/architecture/transactions.md
This PR describes new transaction execution mechanics introduced in v0.6.
https://wiki.bf.local/display/EXN/Transaction+status
> Update transaction execution info and description of relevant HTTP APIs

- src/architecture/serialization.md
This PR fixes problems with the serialization article pointed out by #193.
> Fix serialization article

- src/advanced/node-management.md
> Update request to add new peer

- src/architecture/configuration.md
Added missing consensus configuration parameter which was present at docs.rs but missing at Exonum.com
> Add missing consensus parameter

- src/advanced/node-management.md
> add state_hash description

- src/advanced/consensus/requests.md
- src/advanced/consensus/specification.md
> reviews consensus docs

- src/advanced/node-management.md
> Update "blocks in range" response example

- src/get-started/install.md
> Update installation guide for Windows

- src/advanced/service-testing.md
- src/architecture/services.md
https://github.com/exonum/exonum/pull/715
> handle_commit -> after_commit

- src/architecture/clients.md
This PR removes a somewhat complicated statement about light client implications, and removes unnecessary formatting from the article.
> Clarify light client article

- src/advanced/time.md
Translation of the Time Oracle section of documentation into Russian.
Sections starting from REST API have been removed according to instructions.
> Translation of the Time Oracle section

- theme/main.html
> include cookiebot

- src/architecture/transactions.md
Document that exonum does not guarantee that transactions are applied in the order of issue
> Document that exonum does not guarantee that transactions are applied… [ECR-391]

- src/advanced/time.md
- src/architecture/storage.md
1. Rewording of a paragraph concerning Exonum Time service according to the service actual behaviour;
2. Update of parameters in Storage document accoring to https://github.com/exonum/exonum/pull/565
> correct error and outdated parameters in docs

- package-lock.json
- package.json
Minor updates to fix low severity vulnerabilities in npm configuration.
> update npm configuration

- misc/cspell.json
- mkdocs.yml
- src/jp.md
> Japanese welcome page

- src/get-started/java-binding.md
I chose `master` as target branch because EJB will be realised earlier than Exonum core.
> Change known limitations of EJB

- src/get-started/java-binding.md
Add a warning about broken ITs on Linux since it's unknown how much it will take to fix them.
> Add a warning about broken ITs on Linux

- src/advanced/node-management.md
Added doc entry for `v1/rebroadcast` endpoint.
> Add doc-entry for rebroadcast endpoint [ECR-2131]

- src/roadmap.md
> new Exonum roadmap

- misc/cspell.json
- src/get-started/java-binding.md
- Changed links to javadoc
- Changed links to github files
- Updated docs where needed
> Exonum doc update for 0.3 version [ECR-2466]

- mkdocs.yml
- src/architecture/services.md
- src/architecture/storage.md
- src/get-started/create-service.md
- src/get-started/data-proofs.md
- src/get-started/install.md
- src/get-started/light-client.md
- src/get-started/what-is-exonum.md
- src/index.md
> Small changes to names of the tutorials

- .github/pull_request_template.md
- .travis.yml
Build any develop (pre-release) branches, such as 'develop-ejb-0.4' on CI.
> Build all develop branches on CI

- misc/cspell.json
- src/get-started/java-binding.md
Document changes after separating transactions and messages.
See also: https://github.com/exonum/exonum-java-binding/pull/574
---
Things to do:
> Document changes after separating tx messages [ECR-2730]

- src/architecture/clients.md
> serialization format quick fix

- src/get-started/java-binding.md
Document standard services provided by the EJB app.
> Document standard services provided by the EJB app [ECR-2819]

- src/get-started/java-binding.md
> EJB v0.4: links update

- src/get-started/java-binding.md
Update links in EJB User Guide to 0.4.
> Update EJB User Guide to 0.4

- src/advanced/node-management.md
> delete comment from node-management doc

- src/advanced/merkelized-list.md
The newer description features new hashing rules that are more sound but are not (yet) implemented in the main repository.
> Revert Merkelized list description

- src/get-started/install.md
> Fix windows protobuf install instruction

- src/get-started/java-binding.md
Add a new line as right now list isn't displayed correctly - https://exonum.com/doc/version/latest/get-started/java-binding/#built-in-services .
> Fix Built-In section in EJB User Guide

- src/get-started/light-client.md
Added reference to Light Client Java.
> Light Client Java reference

- src/get-started/install.md
Windows support is considered experimental at the moment. Due to lack of proper testing on different Windows versions and in different environments.
> Add note about Windows support

- src/get-started/create-service.md
> Cryptocurrency tutorial 0.10

- src/advanced/node-management.md
> Node management 0.10

- src/get-started/data-proofs.md
> Update Cryptocurrency Advanced tutorial to 0.10 version

- package-lock.json
- src/get-started/java-binding.md
> [ECR-3034] Update doc for build-in services configuration

- src/roadmap.md
> Roadmap Update

- src/glossary.md
> Update definitions to v0.10

- src/get-started/create-service.md
- src/get-started/data-proofs.md
> Introduce some clarifications into the texts

- src/index.md
> update home page to 0.10 version

- src/advanced/node-management.md
> Update healthcheck response

- src/get-started/timestamping-tutorial.md
> Update generate-config and run commands

- src/advanced/network.md
- src/advanced/node-management.md
> Add info on WebSocket

- src/get-started/java-binding.md
See https://github.com/exonum/exonum-java-binding/pull/848 for details.
> Remove obsolete warning [ECR-942]

- versioned.js
> Jenkins fix

- src/get-started/java-binding.md
> Update docs with the recent changes in packaging [ECR-2990]

- src/get-started/timestamping-tutorial.md
> Update `generate-config` command

- src/get-started/java-binding.md
Also updated versions in archetype usage instructions.
> Bump versions in links to files and API docs [EJB-0.6.0]

- src/advanced/configuration-updater.md
- src/architecture/configuration.md
> Fix service name and indentation

- README.md
- src/advanced/bitcoin-anchoring-without-segwit.md
- src/advanced/bitcoin-anchoring.md
- src/advanced/consensus/specification.md
- src/advanced/network.md
- src/advanced/node-management.md
- src/advanced/time.md
- src/architecture/configuration.md
- src/get-started/create-service.md
- src/get-started/design-overview.md
- src/get-started/install.md
- src/get-started/timestamping-tutorial.md
- src/glossary.md
- src/roadmap.md
A link to ../architecture/merkledb.md#merkelized-indices will be available after merging #319
> Fixes some dead links

- src/get-started/java-binding.md
> Mention Homebrew repository in EJB installation instructions [ECR-3129]

- src/get-started/java-binding.md
> Fix broken markdown

- src/get-started/java-binding.md
> empty lines are evil

- src/get-started/install.md
> Correct Dependencies List

- theme/assets/stylesheets/extra.css
> Change extra css for new website

- misc/cspell.json
- src/advanced/network.md
- src/glossary.md
> Correct number of validators

- src/roadmap.md
> Updates to implementation schedule

- src/get-started/install.md
> adjust dependencies for ver 0.11

- misc/cspell.json
- src/advanced/network.md
- src/glossary.md
- src/roadmap.md
> Delete excess tasks from quarter 3

- src/advanced/service-testing.md
- src/get-started/java-binding.md
- src/get-started/test-service.md
Add Java TestKit documentation.
Should we create 0.7.0 branch and target this PR into 0.7.0?
Should there be an example of complete test that uses TestKit and demonstrates most of the features?
> Add Java TestKit documentation [ECR-3057]

- src/get-started/java-binding.md
> Add logging configuration info

- src/architecture/merkledb.md
Add a missing link to `Patch`.
> Add a missing documentation link

- theme/assets/stylesheets/extra.css
> new colors

- misc/cspell.json
- src/advanced/network.md
> Add info on Noise protocol

- .travis.yml
- README.md
- src/advanced/network.md
- src/architecture/configuration.md
- src/get-started/design-overview.md
> correct links plus tiny fixes

- src/advanced/node-management.md
> Update stats endpoint

- src/get-started/java-binding.md
> Add a note about supported Libsodium version

- src/get-started/java-binding.md
Update links and terminology in EJB documentation.
> Update links and terminology in EJB documentation

- src/get-started/java-binding.md
Rephrase state hashes paragraph.
> Review fixes EJB 0.8

- src/get-started/java-binding.md
Bump EJB version to 0.8.0 and update Javadoc links.
> Bump EJB version to 0.8.0 and update Javadoc links

- src/get-started/java-binding.md
> Fix example endpoint in External API section

- src/advanced/node-management.md
- src/get-started/light-client.md
> Small docs fix

- src/advanced/node-management.md
- src/get-started/light-client.md
> Fix fields order in node management doc; correct library in LC tutorial

- theme/assets/stylesheets/extra.css
> Change sidebar color for header and github `exonum-doc` [ECR-3789]

- src/advanced/node-management.md
Correct post example for the "Shutdown" endpoint. Delete the "Rebroadcast" endpoint.
> Adjust Endpoints List

- src/advanced/node-management.md
> Add a notice about an order of transactions

- src/advanced/node-management.md
> Escape quote

- src/get-started/java-binding.md
> correct grammar in the EJB guide

- misc/cspell.json
- src/get-started/java-binding.md
> Add Javadoc link

- src/get-started/java-binding.md
- Changes in service implementation
- Updated transaction processing documentation
- Added Schema example
- Added Configuration and Reconfiguration
The documentation on Testkit, Node configuration,
service deploy and instantiation are updated
separately.
> Update the documentation for dynamic services:

- src/get-started/java-binding.md
Update Java TestKit documentation with support of DS.
> Update Java TestKit documentation [ECR-3573]

- src/get-started/java-binding.md
> Set Java Binding version to 0.9.0-rc2

- misc/cspell.json
- src/get-started/java-binding.md
Improved section about Exonum Java Binding.
> Improve section about Exonum Java Binding [ECR-3855].

- misc/cspell.json
- mkdocs.yml
- src/advanced/service-interaction.md
- src/advanced/supervisor.md
- src/architecture/services.md
- src/roadmap.md
This PR adds a *Service Interaction* article which describes interaction among Exonum services.
See: https://jira.bf.local/browse/ECR-4158
> Describe service interaction [ECR-4158]

- src/get-started/create-service.md
- src/get-started/data-proofs.md
This PR updates the advanced cryptocurrency tutorial.
See: https://jira.bf.local/browse/ECR-4178
> Update advanced tutorial [ECR-4178]

- src/advanced/bitcoin-anchoring.md
> Brush up anchoring article

- src/get-started/test-service.md
> Update test cryptocurrency service doc [ECR-4180]

- src/get-started/create-service.md
- src/get-started/test-service.md
This PR performs minor brush-up of the testing tutorial after #397.
> Brush up testing tutorial

- .travis.yml
- README.md
- dev-requirements.txt
- misc/lint.sh
- mkdocs.yml
- requirements.lock
- requirements.txt
- src/get-started/create-service.md
- src/get-started/data-proofs.md
- src/get-started/java-binding.md
- theme/main.html
This PR updates cryptocurrency tutorials to reflect changes brought by exonum/exonum#1765.
------
See: https://jira.bf.local/browse/ECR-4219
> Update tutorials with built-in service instances [ECR-4219]

- src/advanced/service-testing.md
- src/get-started/create-service.md
- src/get-started/data-proofs.md
- src/get-started/light-client.md
- src/get-started/test-service.md
This PR updates used crate versions to the release candidate version.
-----
See: https://jira.bf.local/browse/ECR-4203
> Change crate versions in tutorials [ECR-4203]

- .travis.yml
- dev-requirements.txt
- misc/lint.sh
- package-lock.json
- package.json
- requirements.txt
- versioned.js
This PR updates Python to 3.7 (2.x is no longer supported) and fix the versioning script.
> Update Python version & fix versioning script

- .travis.yml
- misc/lint.sh
- package-lock.json
- package.json
- src/advanced/consensus/specification.md
- src/advanced/merkelized-list.md
- src/advanced/other-services.md
- src/architecture/consensus.md
- src/architecture/merkledb.md
- src/architecture/serialization.md
- src/architecture/services.md
- src/architecture/transactions.md
- src/es.md
- src/get-started/create-service.md
- src/get-started/data-proofs.md
- src/get-started/design-overview.md
- src/get-started/install.md
- src/get-started/java-binding.md
- src/get-started/what-is-exonum.md
- src/glossary.md
- src/jp.md
- src/roadmap.md
This PR changes the link checker to a more comprehensive / modern one.
> New link checker

- src/get-started/java-binding.md
Also use a link to PyPI instead of link to the repo readme (they are identical)
> Mention supervisor mode

- src/advanced/network.md
- src/advanced/other-services.md
- src/advanced/supervisor.md
- src/advanced/time.md
This PR references API docs for service in an explicit way, so they can be found by readers easier.
> Reference service API docs

- src/get-started/java-binding.md
Move the remaining examples to the ejb repo. See also: https://github.com/exonum/exonum-java-binding/pull/1471
> Move other examples [ECR-4257]

- src/advanced/bitcoin-anchoring.md
- src/advanced/consensus/requests.md
- src/advanced/consensus/specification.md
- src/architecture/consensus.md
- src/glossary.md
This PR describes changes in the consensus algorithm brought by exonum/exonum#1820.
---
See also: https://jira.bf.local/browse/ECR-4367
> Customize propose [ECR-4367]

- src/get-started/java-binding.md
- Document that standard services com pre-deployed
- Add a tip on standard services coordinates discovery
> Improve standard services docs

- src/get-started/first-java-service.md
- src/get-started/java-binding.md
> Add action field to launcher configs examples

- .gitignore
- README.md
> Fix build Instruction

- src/architecture/configuration.md
- src/get-started/install.md
- src/get-started/java-binding.md
> Add jq util in a list of installed dependencies [ECR-1285]

- misc/cspell.json
- mkdocs.yml
- src/advanced/other-services.md
- src/advanced/service-testing.md
- src/architecture/transactions.md
- src/get-started/create-service.md
- src/get-started/data-proofs.md
- src/get-started/migrate-service.md
- src/get-started/test-service.md
This PR adds a migration tutorial.
---
See: https://jira.bf.local/browse/ECR-4182
> Migration tutorial [ECR-4182]
