- src/get-started/install.md
To cargo install a version, we need the `--vers` option; not `--version`
> Wrong command line option for version

- misc/lint.sh
Fixes broken Travis build associated with a newly released `mkdocs-material` version.
> Get rid of Unicode-related false alarm

- src/architecture/services.md
...from `handle_genesis_block()` to `initialize()` according to changes in Exonum core.
> Rename service initialization handler

- src/advanced/node-management.md
- src/architecture/transactions.md
This PR clarifies `Transaction.info()` behavior and its use in the blockchain explorer.
Related to exonum/exonum#343.
> Transaction info clarifications

- src/advanced/node-management.md
Imagine, you have a chain with empty first 1001 blocks, you want to retrieve all non-empty blocks. You pull blocks starting from 0 with increment of 1000. There is no way to say whether you have exhausted all blocks in the chain or you haven't reached non-empty blocks yet. So should you keep pulling or stop? Thus one needs to start pulling from the end until 0 is reached. It is unclear from the documentation that skipping the `latest` param will result in a pull from the very end of the chain.
> Clarify parameters for the blocks-in-range request

- src/advanced/consensus/specification.md
- src/advanced/network.md
The library has changed from from `mio` to `tokio` in exonum/exonum#300.
> Update info on event processing library

- src/architecture/services.md
- src/architecture/storage.md
- src/get-started/create-service.md
- src/get-started/design-overview.md
- src/get-started/install.md
- src/glossary.md
This PR updates information in docs about the persistence engine used by Exonum. In particular, LevelDB support is mentioned as removed.
> Update info on persistence according to 0.3 changes

- mkdocs.yml
- requirements.lock
- requirements.txt
- theme/assets/stylesheets/extra.css
- theme/main.html
This PR updates documentation to the newest version of `mkdocs-material`. It looks pretty neat:
The only problem I have with the update is that the links on the right navigation (Table of Contents) panel flicker on hover in Firefox (57.0.2, Win 8.1). This seems to be a trouble with the Firefox rendering engine (specifically, processing of a combination of `transform` and `transition` CSS attributes), not the theme, though.
> Theme update

- src/get-started/install.md
This PR answers a somewhat frequent question which Rust version(s) Exonum supports.
> Add note about supported Rust versions

- src/get-started/create-service.md
Although endpoints for transactions were updated in the code excerpts, the old ones are still used in `curl`-based testing in the end of the tutorial.
> Fix URLs for POST requests in service manual

- src/advanced/service-testing.md
This PR replaces the "Service Testing" page with the (slightly polished) tutorial from [the `exonum-testkit` repo](https://github.com/exonum/exonum-testkit/blob/v0.1.1/TUTORIAL.md).
> Update service testing page

- src/architecture/services.md
This PR rewrites `Service::state_hash` documentation according to changes in the Exonum repo.
> Update `state_hash` description

- src/advanced/node-management.md
- src/architecture/transactions.md
- src/get-started/create-service.md
This PR removes mentions of `Transaction::info` throughout documentation. The mentions in the tutorial are removed too; although the tutorial code itself is not yet updated, the changes are fairly predictable.
Closes #147.
> Remove `Transaction::info` mentions

- src/contributing.md
The exonum documentation looks & reads nice, but it uses far too much formatting. A clear example is this "note". This special-format sections should be kept minimal, reserved for really critical information (e.g.: "Security" and "Privacy").
> Remove unnecessary "!!! note" mkdocs tag

- src/contributing.md
This PR adds a mention of documentation as a contribution option, and removes a superfluous tip about git.
See #160 and #161 for context.
> Contributing clarifications

- src/get-started/install.md
This PR details to what extent Exonum supports Windows. The previously used wording could be interpreted as if Exonum *will* not run on Windows (which is not true, it *may* encounter problems in certain setups).
> Expand on Windows support

- src/advanced/service-testing.md
- src/get-started/test-service.md
This PR fixes version of the `exonum-testkit` crate mentioned on 2 occasions.
> Update testkit crate version

- src/architecture/services.md
This PR removes the `'static` lifetime from the `service_name` method. For now, it is confined to the service page; the remaining mention in the Create Service tutorial can be dealt with separately.
Related to exonum/exonum#485.
> Remove static lifetime specifier for `service_name`

- src/advanced/node-management.md
- src/architecture/serialization.md
This PR removes remaining `network_id` mentions from the docs.
> Remove `network_id` mentions

- src/get-started/java-binding.md
Downside of this change - we're going to need to update this field each release for now.
> Add archetypeVersion option in get-started/java-binding [ECR-1882]

- src/get-started/java-binding.md
@dmitry-timofeev Do we want to do something about such links as https://github.com/exonum/exonum-java-binding/blob/v0.1/exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/ApiControllerTest.java ? Do we want to change them to latest version manually each release? Or change `v0.1` to `master`? Or just leave it be?
> Use latest EJB version in Javadoc

- src/advanced/consensus/specification.md
- src/architecture/configuration.md
- src/architecture/consensus.md
https://github.com/exonum/exonum/pull/848
> Introduce round timeout increase in docs.

- .travis.yml
- misc/cspell.json
- src/get-started/java-binding.md
Adds documentation about `Service#afterCommit` usage.
> Document Service#afterCommit handler [ECR-2728]

- src/get-started/java-binding.md
Add Core Schema API section to EJB User Guide.
> Add Core Schema API to EJB User Guide [ECR-2727]

- src/get-started/install.md
Dependencies to protobuf in v0.10.x
> Update install.md to protobuf

- src/advanced/merkelized-list.md
New hashing rules for `ProofListIndex` based on [Certificate Trasparency](https://tools.ietf.org/html/rfc6962#section-2.1) specification.
> New hashing rules in ProofListIndex

- src/get-started/java-binding.md
Fix artifact versions according to the published
one. Also, add missing parameter to
archetype:generate.
> Fix artifact versions

- versioned.js
Investigation shown that Jenkins checks out to master in the form of `git checkout -f <commit_id>`, therefore git.getBranchName() returns string which doesn't contain branch name and looks something like `(HEAD detached at 5cc110e)`. This is why the script fails during the git.checkout(returnToBranch) call.
Now it checks for environment variable BUILD_ENVIRONMENT and if it set to 'jenkins' the script assumes that it is running in the automated environment and doesn't perform branch preservation.
> Fixed Jenkins build issue

- src/get-started/install.md
This PR removes outdated information about running sandbox tests for Exonum from the installation guide.
> Update instructions on running tests

- src/advanced/time.md
- src/get-started/java-binding.md
Update EJB time oracle documentation.
https://github.com/exonum/exonum-java-binding/tree/master/exonum-java-binding/time-oracle link is not yet valid, but will be after https://github.com/exonum/exonum-java-binding/pull/754 is merged.
> Add EJB time oracle documentation [ECR-2896]

- src/get-started/java-binding.md
Make it a single list instead of three separate lists
(when rendered on the page):
> Fix the list of services

- src/advanced/service-testing.md
Fix for testkit documentation example.
> Use is_tx_in_pool() instead of mempool().contains_key()

- src/get-started/install.md
On some old Ubuntu versions RocksDB shows unpredictable behavior for EJB, and all our CI is done using RocksDB 5.17. To avoid bugs, we should mention this fact in the docs.
> Add info about installing librocksdb from our PPA [ECR-3040]

- src/get-started/install.md
Here used to be a russian 'с' letter
> Fix invalid letter in choko install command

- src/roadmap.md
After discussion in the team, @aleksuss suggested renaming Merkle DB to Exonum MerkleDB.
> Rename "Merkle DB" to "Exonum MerkleDB" in roadmap

- src/get-started/java-binding.md
It has been discovered that the packaging
procedure does not produce RocksDB-independent
binary (java_bindings library), hence the app users
must install RocksDB on macOS.
> Require rocksdb (temporarily) [ECR-3169]

- src/get-started/java-binding.md
Fix the typo and change link to the documentation website.
> Fix the link to libsodium

- src/get-started/java-binding.md
Starting from release 0.7.0 we will link RocksDB statically on Mac.
> Remove rocksdb from requirements as it will be linked statically. [ECR-3324]

- src/get-started/java-binding.md
Remove link to MemoryDb in Java Binding doc (not used).
> Remove link to MemoryDb [ECR-3315]

- src/get-started/java-binding.md
Removes requirement of setting `PATH` and `LD_LIBRARY_PATH` variables. Valid only for 0.7 with [this fix](https://github.com/exonum/exonum-java-binding/pull/1040)
> Update EJB installation guide for 0.7

- src/get-started/install.md
The installation instruction is invalid. Our package `librocksdb5.17` from Exonum PPA installs library files into `/usr/lib`, not into `/usr/lib/x86_64-linux-gnu`. So with current instructions RocksDB is always compiled from sources. Valid `ROCKSDB_LIB_DIR` is also used in our Travis configuration: https://github.com/exonum/exonum/blob/master/.travis.yml#L59
Spotted when testing EJB on Linux by @dip56
> Fix invalid ROCKSDB_LIB_DIR in installation guide

- src/advanced/node-management.md
Correct the meaning of the `end` field of the response for the "Blocks in Range" endpoint.
https://jira.bf.local/browse/ECR-3187
> Correct value of the `end` field [ECR-3187]

- src/get-started/java-binding.md
Are we going to release `0.9.0`, not `0.9.0-rc1` or smth?
> Fix version numbers for the new 0.9.0-rc1 release [ECR-3963]

- src/get-started/install.md
Exonum now uses RocksDB 6.2, not 5.17. Using correct package is important when building EJB App from sources.
> Use correct rocksdb package in installation instructions

- src/get-started/java-binding.md
> Clarify that Exonum Java uses a separate port [ECR-3856]

- src/get-started/light-client.md
This PR updates the light client tutorial and removes links to the timestamping tutorial (which will be removed). The tutorial is slightly sketchy; it's based not on the actual code, but on my assumptions on how it should be written.
-----
See: https://jira.bf.local/browse/ECR-4179
> Update light client tutorial [ECR-4179]

- src/advanced/merkelized-list.md
This PR fixes description of how `ProofListIndex` is stored in MerkleDB.
-----
See: https://jira.bf.local/browse/ECR-4194
> Fix `ProofListIndex` storage details [ECR-4194]

- .gitignore
- .gitmodules
- .travis.yml
- README.md
- mkdocs.yml
- package-lock.json
- package.json
- requirements.lock
- requirements.txt
- src/get-started/HelloWorld.java
- src/get-started/java-binding.md
- versioned.js
Adds a plugin to include Java code examples from source files.
Adds Exonum Java Binding as a Git submodule, to be able to include the code snippets from its source.
1. Shall we use a git submodule or add a script syncing particular directories from EJB repository? Potentially, it will allow to reduce the paths lenghts, but will add 'accidental' changes to the diff (changes that have already been reviewed during the modifications in the main repository).
- ECR-4250
- ECR-4132
- ECR-4258
> Add Java code examples [ECR-4250]

- src/get-started/java-binding.md
Update the documentation on service development (no testing — see ECR-4256).
There are a couple of questions (@slowli ) marked with todo comments.
Some high-level questions/considerations:
- I am not quite happy with the section on schema definition — it lacks some structure.
- Shall we keep the sections on transaction messages and lifecycle for integrity, or just link the main sections?
Might be more convenient to review commit-by-commit.
> Update java service dev docs for 0.10 [ECR-4241]

- misc/cspell.json
- requirements.lock
- requirements.txt
- src/get-started/java-binding.md
Update the testkit code examples and move them to the
main EJB repository.
> Update the Java testing documentation for 0.10 [ECR-4256]:

- src/get-started/first-java-service.md
As tutorial code depends on both EJB and JLC (which,
in turn, depends on EJB messages and common library),
it cannot always be completed when _just_ EJB is released —
it may need a compatible JLC release also (if the previous
does not work with the new EJB). Hence, it have to
use a separate Git tag, that is set when both EJB and JLC
are released.
See the entries in the release procedure for details:
https://wiki.bf.local/display/EJB/Java+Binding+Release+Checklist+Template
> Use a separate tag for tutorial code:

- requirements.txt
This library has sat unpublished for too long, but I've now _finally_ published it to PyPI 😅 
Please migrate to the published version ASAP, so that you can control exposure to new updates as I merge them over on the main git repository.
> Use PyPI published mkdocs-codeinclude-plugin
